
#db config for deployment on server
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Kalisari13790

server:
  port: 9000
  
  #ORM s/w specific properties
jpa:
  database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
  generate-ddl: true
  show-sql: ture
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      globally_quoted_identifiers: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      format-sql: true
sql:
  init:
    mode: always
    continue-on-error: false